project:
  type: website
  output-dir: docs

website:
  title: "How to Start Your Own Code Club"
  page-navigation: true
  sidebar: false

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    self-contained: true
    theme: style.scss
