project:
  type: website
  output-dir: docs

website:
  title: "How to Start Your Code Club"
  site-url: "https://yourusername.github.io/your-repo-name"
  repo-url: "https://github.com/SORTEE/start-your-codeclub-guide"
  repo-actions: [edit, issue]
  page-navigation: true

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    self-contained: true
    theme: style.scss
